[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -p no:web3 -p no:web3.tools -p no:web3.tools.pytest_ethereum -p no:pytest_ethereum
